### ISSUE TITLE
什么时候上架到Chrome应用商店

### ISSUE THREAD

**Issue by Hoexhe** [Yuxiaoy1/nonstop#1]
很赞的插件，如果到上架到Chrome应用商店就更方便了

**Comment by Yuxiaoy1** [comment]
@Hoexhe Chrome 应用商店上架比较麻烦，抱歉暂不考虑。
你还可以通过在 Chrome 浏览器加载 [crx](https://github.com/Yuxiaoy1/nonstop/releases) 文件添加此扩展，谢谢。

**Comment by Yuxiaoy1** [comment]
@Hoexhe 使用 crx 文件添加会有问题，最新方案请参考 https://github.com/Yuxiaoy1/nonstop/releases
