### ISSUE TITLE
Con't use “crx”

### ISSUE THREAD

**Issue by Yueshi9** [Yuxiaoy1/nonstop#2]
“If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.”

The info is provided by Chrome

**Comment by Yuxiaoy1** [comment]
@Yueshi9 Chrome 目前不支持非谷歌官方商店的扩展程序了。
可行的更新后的方案为加载解压缩的文件夹，具体可查看最新 [release](https://github.com/Yuxiaoy1/nonstop/releases)。

**Comment by Yueshi9** [comment]
THX
